import {$,$$,setPhotos,setSelected,selectedServiceId} from "./core.js";import {initStorage,getServices} from "./storage.js";import {initEquipment} from "./equipment.js";import {renderDashboard,renderHistory} from "./dashboard.js";import {showView,openNew,selectMode} from "./navigation.js";
window.showView=showView;
window.openNew=openNew;import {saveService} from "./services.js";import {initSupabase,syncPending,updateConnection} from "./sync.js";import {escapeHTML,formatDate,toast} from "./core.js";
import {initDiagnostics} from "./diagnostics.js";
function openModal(id){const x=getServices().find(s=>s.id===id);if(!x)return;setSelected(id);$("#modalTitle").textContent="Servicio "+x.id;$("#modalBody").innerHTML=`<div class="preview-grid"><div><small>N.º DE SERVICIO</small><strong>${escapeHTML(x.id)}</strong></div><div><small>FECHA</small><strong>${formatDate(x.createdAt)}</strong></div><div><small>EQUIPO</small><strong>${escapeHTML(x.brand)} ${escapeHTML(x.model)}</strong></div><div><small>CLIENTE</small><strong>${escapeHTML(x.client||"No indicado")}</strong></div><div><small>N.º DE SERIE</small><strong>${escapeHTML(x.serial||"No indicado")}</strong></div><div><small>ESTADO</small><strong>${escapeHTML(x.status)}</strong></div></div><div class="preview-block"><small>PROBLEMA INFORMADO</small><p>${escapeHTML(x.problem||"—")}</p></div><div class="preview-block"><small>TRABAJO</small><p>${escapeHTML((x.work||[]).join(" · ")||"No indicado")}</p>${x.workDetail?`<p>${escapeHTML(x.workDetail)}</p>`:""}</div><div class="preview-block"><small>RESPONSABLES</small><p>${escapeHTML((x.technicians||[]).join(" · ")||"No indicados")}</p></div>`;$("#modalEdit").classList.remove("hidden");$("#modalDelete").classList.remove("hidden");$("#modalPreview").classList.remove("hidden");$("#modalPreview").textContent="▣ Previsualizar comprobante";$("#serviceModal").classList.remove("hidden");$("#serviceModal").setAttribute("aria-hidden","false")}
function closeModal(){$("#serviceModal").classList.add("hidden");$("#serviceModal").setAttribute("aria-hidden","true")}
function edit(id){const x=getServices().find(s=>s.id===id);if(!x)return;import("./core.js").then(c=>c.setEditing(id));closeModal();showView("new-service");selectMode(x.mode||"quick");const f=$("#serviceForm");f.elements.brand.value=x.brand||"";f.elements.model.value=x.model||"";f.elements.client.value=x.client||"";f.elements.serial.value=x.serial||"";f.elements.problem.value=x.problem||"";f.elements.workDetail.value=x.workDetail||"";f.elements.condition.value=x.condition||"";f.elements.accessories.value=x.accessories||"";f.elements.observations.value=x.observations||"";$$('input[name="work"]').forEach(i=>i.checked=(x.work||[]).includes(i.value));$$('input[name="technician"]').forEach(i=>i.checked=(x.technicians||[]).includes(i.value));toast("Editando "+x.id)}
function del(id){const x=getServices().find(s=>s.id===id);if(!x||!confirm("¿Eliminar el servicio "+x.id+"?"))return;import("./storage.js").then(m=>{m.writeServices(getServices().filter(s=>s.id!==id));closeModal();renderDashboard();renderHistory();toast("Servicio "+id+" eliminado.")})}
function preview(id){const x=getServices().find(s=>s.id===id);if(!x)return;$("#modalTitle").textContent="Previsualización · "+x.id;$("#modalBody").innerHTML=`<div class="receipt-preview"><div class="receipt-brand"><strong>LEO-TECH</strong><span>SERVICE</span></div><div class="receipt-number">COMPROBANTE #${escapeHTML(x.id)}</div><hr><p><b>Equipo:</b> ${escapeHTML(x.brand)} ${escapeHTML(x.model)}</p><p><b>Cliente:</b> ${escapeHTML(x.client||"No indicado")}</p><p><b>Serie:</b> ${escapeHTML(x.serial||"No indicado")}</p><p><b>Problema:</b> ${escapeHTML(x.problem||"—")}</p><p><b>Trabajo:</b> ${escapeHTML((x.work||[]).join(", ")||"No indicado")}</p><p><b>Descripción:</b> ${escapeHTML(x.workDetail||"No indicada")}</p><p><b>Responsables:</b> ${escapeHTML((x.technicians||[]).join(", ")||"No indicados")}</p><p><b>Estado:</b> ${escapeHTML(x.status)}</p><p><b>Recibido:</b> ${formatDate(x.createdAt)}</p><p><b>Observaciones:</b> ${escapeHTML(x.observations||"No indicadas")}</p></div>` ;$("#modalEdit").classList.add("hidden");$("#modalDelete").classList.add("hidden");$("#modalPreview").textContent="Cerrar";$("#modalPreview").onclick=closeModal;$("#serviceModal").classList.remove("hidden")}
function bind(){
  const dt=$("#diagnosticToggle"),dp=$("#diagnosticPanel"),dc=$("#diagnosticClose"),cl=$("#diagnosticClear");
  dt?.addEventListener("click",()=>dp?.classList.toggle("open"));
  dc?.addEventListener("click",()=>dp?.classList.remove("open"));
  cl?.addEventListener("click",()=>window.LEOTECH_DIAG?.clear());document.addEventListener("click",e=>{const n=e.target.closest(".nav-item");if(n){e.preventDefault();e.stopPropagation();showView(n.dataset.view);if(innerWidth<=800)$(".sidebar")?.classList.remove("open");return}const r=e.target.closest(".service-clickable");if(r){openModal(r.dataset.serviceId);return}});const serviceForm=$("#serviceForm"); serviceForm?.addEventListener("submit",saveService); $("#saveServiceBtn")?.addEventListener("click",()=>saveService({preventDefault(){},target:serviceForm,submitter:$("#saveServiceBtn")})); $("#saveNext")?.addEventListener("click",()=>saveService({preventDefault(){},target:serviceForm,submitter:$("#saveNext")}));$("#closeModal")?.addEventListener("click",closeModal);$("#serviceModal")?.addEventListener("click",e=>{if(e.target.id==="serviceModal")closeModal()});$("#modalEdit")?.addEventListener("click",()=>edit(selectedServiceId));$("#modalDelete")?.addEventListener("click",()=>del(selectedServiceId));$("#modalPreview")?.addEventListener("click",()=>preview(selectedServiceId));$("#headerNew")?.addEventListener("click",openNew);$("#heroNew")?.addEventListener("click",openNew);$("#cancelForm")?.addEventListener("click",()=>showView("dashboard"));$("#mobileMenu")?.addEventListener("click",()=>$(".sidebar")?.classList.toggle("open"));$$(".mode").forEach(b=>b.addEventListener("click",()=>selectMode(b.dataset.mode)));$("#servicePhotos")?.addEventListener("change",e=>{setPhotos([...e.target.files]);const box=$("#photoPreview");box.innerHTML="";[...e.target.files].forEach(f=>{const i=document.createElement("img");i.src=URL.createObjectURL(f);i.alt="Foto del equipo";box.appendChild(i)})})}
document.addEventListener("DOMContentLoaded",async()=>{initDiagnostics();bind();await initStorage();selectMode("quick");initEquipment();renderDashboard();renderHistory();updateConnection();await initSupabase();await syncPending();updateConnection();})
