const KEY="leoTechSheetsUrl";const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let equipment=[],lastBatch=[];
const works=["Instalación de Windows","Instalación de programas","Mantenimiento general","Cambio/Ampliación de RAM","Cambio de SSD","Reparación","Diagnóstico"];

function norm(v){return String(v??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"")}
function excelValue(row,names){const keys=Object.keys(row);const key=keys.find(k=>names.includes(norm(k)));return key?String(row[key]??"").trim():""}
function importExcel(file){const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:"array"});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});if(!rows.length){$("#msg").textContent="⚠ El Excel está vacío.";$("#msg").className="err";return}const imported=rows.map(r=>({brand:excelValue(r,["marca","brand"]),model:excelValue(r,["modelo","model"]),serial:excelValue(r,["numerodeserie","nserie","serie","serial"]),problem:excelValue(r,["problema","problemainformado","falla"]),work:excelValue(r,["trabajo","trabajorealizado","servicio"]),status:excelValue(r,["estado"])||"En proceso",observations:excelValue(r,["observaciones","observacion"])})).filter(x=>x.brand||x.model||x.serial||x.problem||x.work);if(!imported.length){$("#msg").textContent="⚠ No encontré datos reconocibles. Usá la plantilla.";$("#msg").className="err";return}equipment=imported;renderEquipment();$("#msg").textContent="✓ Se cargaron "+imported.length+" equipos desde Excel.";$("#msg").className="ok"}catch(err){console.error(err);$("#msg").textContent="⚠ No se pudo leer el Excel.";$("#msg").className="err"}};reader.readAsArrayBuffer(file)}
function downloadTemplate(){const rows=[{Marca:"Lenovo",Modelo:"IdeaPad 3", "N.º de serie":"ABC123",Problema:"No enciende",Trabajo:"Diagnóstico",Estado:"En proceso",Observaciones:""}];const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Equipos");XLSX.writeFile(wb,"LEO-TECH-plantilla-equipos.xlsx")}
function url(){return(localStorage.getItem(KEY)||"").trim()} function configure(){const v=prompt("Pegá la URL /exec de tu Google Apps Script:",url());if(v!==null){localStorage.setItem(KEY,v.trim());updateStatus()}}
function updateStatus(){const ok=!!url();$("#status").textContent=ok?"● Google Sheets configurado":"● Sin configurar";$("#status").className=ok?"ok":""}
function code(){return"LT-"+Date.now().toString().slice(-8)+"-"+String(Math.floor(Math.random()*90)+10)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function addEquipment(){equipment.push({brand:"",model:"",serial:"",problem:"",work:"",status:"En proceso",observations:""});renderEquipment()}
function renderEquipment(){const box=$("#equipmentList");$("#count").textContent=equipment.length;box.innerHTML=equipment.map((x,i)=>'<div class="equipment"><div class="equipmentHead"><strong>Equipo '+(i+1)+'</strong>'+(equipment.length>1?'<button type="button" class="danger" onclick="removeEquipment('+i+')">✕ Quitar</button>':"")+'</div><div class="equipmentGrid"><label>Marca<input data-i="'+i+'" data-k="brand" value="'+esc(x.brand)+'" list="brands"></label><label>Modelo<input data-i="'+i+'" data-k="model" value="'+esc(x.model)+'"></label><label>N.º de serie<input data-i="'+i+'" data-k="serial" value="'+esc(x.serial)+'"></label><label>Estado<select data-i="'+i+'" data-k="status"><option '+(x.status==="En proceso"?"selected":"")+'>En proceso</option><option '+(x.status==="Terminado"?"selected":"")+'>Terminado</option><option '+(x.status==="Entregado"?"selected":"")+'>Entregado</option></select></label><label class="full">Problema informado<textarea data-i="'+i+'" data-k="problem" rows="2">'+esc(x.problem)+'</textarea></label><label class="full">Trabajo realizado<input data-i="'+i+'" data-k="work" value="'+esc(x.work)+'" list="works"></label><label class="full">Observaciones<textarea data-i="'+i+'" data-k="observations" rows="2">'+esc(x.observations)+'</textarea></label></div></div>').join('')+'<datalist id="brands"><option>Lenovo</option><option>HP</option><option>ASUS</option><option>Acer</option><option>Dell</option><option>Samsung</option><option>Apple</option><option>Positivo</option><option>Exo</option><option>GIGABYTE</option></datalist><datalist id="works">'+works.map(w=>'<option>'+w+'</option>').join('')+'</datalist>';box.querySelectorAll("[data-i]").forEach(el=>el.oninput=()=>{equipment[+el.dataset.i][el.dataset.k]=el.value})}
window.removeEquipment=i=>{equipment.splice(i,1);renderEquipment()}
function collect(){return equipment.map(x=>({...x,client:$("#client").value,technician:$("#technician").value}))}
function renderPDF(batch){$("#rCode").textContent=batch.length+" equipos · "+new Date().toLocaleString("es-PY");$("#receiptBody").innerHTML=batch.map((d,i)=>'<div class="receiptItem"><h3>Equipo '+(i+1)+' · '+esc(d.code)+'</h3>'+Object.entries({Cliente:d.client||"—",Marca:d.brand,Modelo:d.model,"N.º de serie":d.serial||"—","Problema":d.problem,"Trabajo":d.work,Responsable:d.technician,Estado:d.status,Observaciones:d.observations||"—"}).map(([k,v])=>'<div class="receiptRow"><strong>'+k+'</strong><span>'+esc(v)+'</span></div>').join('')+'</div>').join('')}
async function saveAll(){if(!url()){configure();if(!url())return}const batch=collect();const bad=batch.findIndex(x=>!x.brand||!x.model||!x.problem||!x.work);if(bad>=0){$("#msg").textContent="⚠ Completá marca, modelo, problema y trabajo del equipo "+(bad+1)+".";$("#msg").className="err";return}batch.forEach(x=>x.code=code());$("#msg").textContent="Enviando "+batch.length+" equipos a Google Sheets…";try{await fetch(url(),{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({batch})});lastBatch=batch;renderPDF(batch);$("#msg").textContent="✓ "+batch.length+" equipos enviados a Google Sheets.";$("#msg").className="ok"}catch(e){$("#msg").textContent="⚠ No se pudo enviar. No se guardaron datos localmente.";$("#msg").className="err"}}
$("#configBtn").onclick=configure;$("#addBtn").onclick=addEquipment;$("#saveBtn").onclick=saveAll;$("#pdfBtn").onclick=()=>{const b=collect();const bad=b.findIndex(x=>!x.brand||!x.model||!x.problem||!x.work);if(bad>=0){$("#msg").textContent="⚠ Completá los datos obligatorios del equipo "+(bad+1)+".";$("#msg").className="err";return}b.forEach(x=>x.code=code());lastBatch=b;renderPDF(b);window.print()};$("#clearBtn").onclick=()=>{$("#client").value="";equipment=[];addEquipment();$("#msg").textContent="";lastBatch=[]};addEquipment();updateStatus();
$("#excelInput").onchange=e=>{if(e.target.files[0])importExcel(e.target.files[0]);e.target.value=""};$("#templateBtn").onclick=downloadTemplate;
