const KEY="leoTechSheetsUrl";const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let equipment=[],lastBatch=[];
const works=["Instalación de Windows","Instalación de programas","Mantenimiento general","Cambio/Ampliación de RAM","Cambio de SSD","Reparación","Diagnóstico"];
function url(){return(localStorage.getItem(KEY)||"").trim()} function configure(){const v=prompt("Pegá la URL /exec de tu Google Apps Script:",url());if(v!==null){localStorage.setItem(KEY,v.trim());updateStatus()}}
function updateStatus(){const ok=!!url();$("#status").textContent=ok?"● Google Sheets configurado":"● Sin configurar";$("#status").className=ok?"ok":""}
function code(){return"LT-"+Date.now().toString().slice(-8)+"-"+String(Math.floor(Math.random()*90)+10)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function addEquipment(){equipment.push({brand:"",model:"",serial:"",problem:"",work:"",status:"En proceso",observations:""});renderEquipment()}
function renderEquipment(){const box=$("#equipmentList");$("#count").textContent=equipment.length;box.innerHTML=equipment.map((x,i)=>'<div class="equipment"><div class="equipmentHead"><strong>Equipo '+(i+1)+'</strong>'+(equipment.length>1?'<button type="button" class="danger" onclick="removeEquipment('+i+')">✕ Quitar</button>':"")+'</div><div class="equipmentGrid"><label>Marca<input data-i="'+i+'" data-k="brand" value="'+esc(x.brand)+'" list="brands"></label><label>Modelo<input data-i="'+i+'" data-k="model" value="'+esc(x.model)+'"></label><label>N.º de serie<input data-i="'+i+'" data-k="serial" value="'+esc(x.serial)+'"></label><label>Estado<select data-i="'+i+'" data-k="status"><option '+(x.status==="En proceso"?"selected":"")+'>En proceso</option><option '+(x.status==="Terminado"?"selected":"")+'>Terminado</option><option '+(x.status==="Entregado"?"selected":"")+'>Entregado</option></select></label><label class="full">Problema informado<textarea data-i="'+i+'" data-k="problem" rows="2">'+esc(x.problem)+'</textarea></label><label class="full">Trabajo realizado<input data-i="'+i+'" data-k="work" value="'+esc(x.work)+'" list="works"></label><label class="full">Observaciones<textarea data-i="'+i+'" data-k="observations" rows="2">'+esc(x.observations)+'</textarea></label></div></div>').join('')+'<datalist id="brands"><option>Lenovo</option><option>HP</option><option>ASUS</option><option>Acer</option><option>Dell</option><option>Samsung</option><option>Apple</option><option>Positivo</option><option>Exo</option><option>GIGABYTE</option></datalist><datalist id="works">'+works.map(w=>'<option>'+w+'</option>').join('')+'</datalist>';box.querySelectorAll("[data-i]").forEach(el=>el.oninput=()=>{equipment[+el.dataset.i][el.dataset.k]=el.value})}
window.removeEquipment=i=>{equipment.splice(i,1);renderEquipment()}
function collect(){return equipment.map(x=>({...x,client:$("#client").value,technician:$("#technician").value}))}
function renderPDF(batch){$("#rCode").textContent=batch.length+" equipos · "+new Date().toLocaleString("es-PY");$("#receiptBody").innerHTML=batch.map((d,i)=>'<div class="receiptItem"><h3>Equipo '+(i+1)+' · '+esc(d.code)+'</h3>'+Object.entries({Cliente:d.client||"—",Marca:d.brand,Modelo:d.model,"N.º de serie":d.serial||"—","Problema":d.problem,"Trabajo":d.work,Responsable:d.technician,Estado:d.status,Observaciones:d.observations||"—"}).map(([k,v])=>'<div class="receiptRow"><strong>'+k+'</strong><span>'+esc(v)+'</span></div>').join('')+'</div>').join('')}
async function saveAll(){if(!url()){configure();if(!url())return}const batch=collect();const bad=batch.findIndex(x=>!x.brand||!x.model||!x.problem||!x.work);if(bad>=0){$("#msg").textContent="⚠ Completá marca, modelo, problema y trabajo del equipo "+(bad+1)+".";$("#msg").className="err";return}batch.forEach(x=>x.code=code());$("#msg").textContent="Enviando "+batch.length+" equipos a Google Sheets…";try{await fetch(url(),{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({batch})});lastBatch=batch;renderPDF(batch);$("#msg").textContent="✓ "+batch.length+" equipos enviados a Google Sheets.";$("#msg").className="ok"}catch(e){$("#msg").textContent="⚠ No se pudo enviar. No se guardaron datos localmente.";$("#msg").className="err"}}
$("#configBtn").onclick=configure;$("#addBtn").onclick=addEquipment;$("#saveBtn").onclick=saveAll;$("#pdfBtn").onclick=()=>{const b=collect();const bad=b.findIndex(x=>!x.brand||!x.model||!x.problem||!x.work);if(bad>=0){$("#msg").textContent="⚠ Completá los datos obligatorios del equipo "+(bad+1)+".";$("#msg").className="err";return}b.forEach(x=>x.code=code());lastBatch=b;renderPDF(b);window.print()};$("#clearBtn").onclick=()=>{$("#client").value="";equipment=[];addEquipment();$("#msg").textContent="";lastBatch=[]};addEquipment();updateStatus();